debug: true

local:
  address: "localhost"
  port: "80"

prod:
  address: "81.200.149.16"
  port: "443"

test_db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "postgres"
  name: "MakeTest"

prod_db:
  host: "147.45.144.230"
  port: "5432"
  name: "default_db"

open_ai_url: "https://api.proxyapi.ru/openai/v1/chat/completions"

smtp:
  host: "smtp.yandex.ru"
  port: "587"